name: cached_blurhash
description: >
  Compact representation of placeholder for an image.
  Encode a blurry image under 30 characters for instant display like used by Medium.
  A fork of flutter_blurhash with added support for image caching using cached_network_image.
version: 0.0.1
homepage: https://github.com/sourabhappdev/cached_blurhash
repository: https://github.com/sourabhappdev/cached_blurhash
issue_tracker: https://github.com/sourabhappdev/cached_blurhash/issues
maintainer: Sourabh Sharma (@sourabhappdev)

screenshots:
  - description: 'Content preview as blurred buffer.'
    path: screenshots/blurred.png
  - description: 'Content loaded.'
    path: screenshots/loaded.png

environment:
  # flutter: ">=3.16.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1

dev_dependencies:

  flutter_lints:

  flutter_test:
    sdk: flutter
